
spring:
  application:
    name:  "loanSystem"
  datasource:
    username: "my_user"
    password: "my_password"
    url: jdbc:postgresql://localhost:5450/my_database
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db/changelog/master.xml
  servlet:
    multipart:
      enabled: on
      max-request-size: 10MB
      max-file-size: 10MB
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123

logging:

  file:
    path: logs
  level:
    root: INFO



jwt:
  secret: "MyVerySecretKeyMyVerySecretKeyMyVerySecretKeyMyVerySecretKeyMyVerySecretKeyMyVerySecretKey"
  expiration: 3600000  # 1 hour in milliseconds
  issuer: "my-app"
  access-token-expiration: 4000
  refreshTokenExpiration: 600009
  refreshSecretKey: refreshSecretKeyrefreshSecretKeyrefreshSecretKeyrefreshSecretKeyrefreshSecretKeyrefreshSecretKeyrefreshSecretKey




rabbitmq:
  exchanges:
    loanDirectExchange: loan.direct.exchange
    loanStatusTopicExchange: loan.topic.exchange
    loanNotificationAlertFanoutExchange : loan.fanout.notification
  queues:
    personalLoanQueue : loan.personal.queue
    carLoanQueue: loan.car.queue
    homeLoanQueue: loan.home.queue
    loanStatusQueue: loan.statusChange.queue
    notificationSmsQueue: loan.notification.sms.queue
    emailNotificationQueue: loan.notification.email.queue
  routingKeys:
    sendLoanWithEmail: loan.email.send
    createLoanPersonal: createLoanPersonal
    createLoanCar: createLoanCar
    createLoanHome: createLoanHome
    loanStatusChange: loan.#
