
spring:
  application:
    name:  "loanSystem"
  datasource:
    username: "my_user"
    password: "my_password"
    url: jdbc:postgresql://localhost:5450/my_database
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db/changelog/master.xml
  jwt:
    secret: This-is-Token
    access-token-expiration: 4000
    refresh-token-expiration: 60000
logging:

  file:
    path: logs
  level:
    root: INFO


jwt:
  secret: "MyVerySecretKeyMyVerySecretKeyMyVerySecretKeyMyVerySecretKeyMyVerySecretKeyMyVerySecretKey"
  expiration: 3600000  # 1 hour in milliseconds
  issuer: "my-app"



